"""empty message

Revision ID: 02a6169b2208
Revises: 
Create Date: 2018-07-15 14:48:25.060887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a6169b2208'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_table', sa.Column('file_path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary_table', 'file_path')
    # ### end Alembic commands ###
